version: 2

models:
  - name: stg_country_metadata
    description: "Standardized country metadata with ISO codes and regional groupings"
    columns:
      - name: country_name
        description: "Official country name"
        tests:
          - not_null
      - name: country_code
        description: "ISO3 country code (primary key)"
        tests:
          - unique
          - not_null
      - name: iso2
        description: "ISO2 country code"
        tests:
          - unique
          - not_null
      - name: continent
        description: "Continent name"
        tests:
          - not_null
      - name: region
        description: "Regional grouping"
        tests:
          - not_null
      - name: income_group
        description: "World Bank income group classification"
        tests:
          - not_null
      - name: is_eu
        description: "European Union membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_oecd
        description: "OECD membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_asean
        description: "ASEAN membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_brics
        description: "BRICS membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_g20
        description: "G20 membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_fcs
        description: "Fragile and conflict-affected situations flag"
        tests:
          - accepted_values:
              values: [0, 1]

  - name: stg_wb_indicators
    description: "Cleaned World Bank economic indicators (28 indicators)"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - relationships:
              to: ref('stg_country_metadata')
              field: country_code
      - name: country_name
        description: "Country name"
        tests:
          - not_null
      - name: year
        description: "Calendar year"
        tests:
          - not_null
      
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - year

  - name: stg_hdr_indicators
    description: "Cleaned UNDP HDR human development indicators (26 indicators)"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - relationships:
              to: ref('stg_country_metadata')
              field: country_code
      - name: country_name
        description: "Country name"
        tests:
          - not_null
      - name: year
        description: "Calendar year"
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - year

  - name: stg_imf_indicators
    description: "Cleaned IMF WEO and FDI indicators (5 indicators)"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - relationships:
              to: ref('stg_country_metadata')
              field: country_code
      - name: year
        description: "Calendar year"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - year
