version: 2

models:
  - name: stg_country_metadata
    description: "Standardized country metadata with ISO codes and regional groupings"
    columns:
      - name: country_name
        description: "Official country name"
        tests:
          - not_null
      - name: country_code
        description: "ISO3 country code (primary key)"
        tests:
          - unique
          - not_null
      - name: iso2
        description: "ISO2 country code"
        tests:
          - unique
          - not_null
      - name: continent
        description: "Continent name"
        tests:
          - not_null
      - name: region
        description: "Regional grouping"
        tests:
          - not_null
      - name: income_group
        description: "World Bank income group classification"
        tests:
          - not_null
      - name: is_eu
        description: "European Union membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_oecd
        description: "OECD membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_asean
        description: "ASEAN membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_brics
        description: "BRICS membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_g20
        description: "G20 membership flag"
        tests:
          - accepted_values:
              values: [0, 1]
      - name: is_fcs
        description: "Fragile and conflict-affected situations flag"
        tests:
          - accepted_values:
              values: [0, 1]

  - name: stg_wb_indicators
    description: "Cleaned World Bank economic indicators (28 indicators)"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - relationships:
              to: ref('stg_country_metadata')
              field: country_code
      - name: country_name
        description: "Country name"
        tests:
          - not_null
      - name: year
        description: "Calendar year"
        tests:
          - not_null
      - name: wb_gdp_ppp_current_intl
        description: "GDP in current international dollars (PPP)"
        tests:
          - column_range:
              min_value: 20000000
              max_value: 50000000000000
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_gdp_growth_annual_pct
      - name: wb_gdp_per_capita_ppp
        description: "GDP per capita based on purchasing power parity"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_agriculture_value_added_pct_gdp
        description: "Agriculture value added as percentage of GDP"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_industry_value_added_pct_gdp 
        description: "Industry value added as percentage of GDP"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_services_value_added_pct_gdp
        description: "Services value added as percentage of GDP"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_exports_pct_gdp
        description: "Exports of goods and services as percentage of GDP"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_imports_pct_gdp
        description: "Imports of goods and services as percentage of GDP"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_population_total
        description: "Total population"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_unemployment_pct
        description: "Unemployment rate percentage"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_labor_force_participation_pct
        description: "Labor force participation rate percentage"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_gini_index
        description: "Gini index of income inequality"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_education_expenditure_pct_gdp
        description: "Education expenditure as percentage of GDP"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: wb_health_expenditure_current_pct_gdp
        description: "Health expenditure as percentage of GDP (current)"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150" 
      - name: wb_health_expenditure_govt_pct
        description: "Government health expenditure as percentage of total health expenditure"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"

      
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - year

  - name: stg_hdr_indicators
    description: "Cleaned UNDP HDR human development indicators (26 indicators)"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - relationships:
              to: ref('stg_country_metadata')
              field: country_code
      - name: country_name
        description: "Country name"
        tests:
          - not_null
      - name: year
        description: "Calendar year"
        tests:
          - not_null
      - name: hdr_human_development_index
        description: "Human Development Index"
        tests:
          - column_range:
              min_value: 0
              max_value: 1
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_gender_inequality_index
        description: "Gender Inequality Index"
        tests:
          - column_range:
              min_value: 0
              max_value: 1
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_gender_development_index
        description: "Gender Development Index"
        tests:
          - column_range:
              min_value: 0
              max_value: 2
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_multidimensional_poverty_index
        description: "Multidimensional Poverty Index"
        tests:
          - column_range:
              min_value: 0
              max_value: 1
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_inequality_coefficient
        description: "Inequality coefficient"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_inequality_income
        description: "Income inequality"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_inequality_education
        description: "Education inequality"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_inequality_life_expectancy
        description: "Life expectancy inequality"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_mean_years_schooling
        description: "Mean years of schooling"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_expected_years_schooling
        description: "Expected years of schooling"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_life_expectancy_years
        description: "Life expectancy at birth (years)"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_labor_force_male_pct
        description: "Male labor force participation rate percentage"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: hdr_labor_force_female_pct
        description: "Female labor force participation rate percentage"
        tests:
          - percentage_value:
              config:
                warn_if: ">0"
                error_if: ">= 150"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - year

  - name: stg_imf_indicators
    description: "Cleaned IMF WEO and FDI indicators (5 indicators)"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - relationships:
              to: ref('stg_country_metadata')
              field: country_code
      - name: year
        description: "Calendar year"
        tests:
          - not_null
      - name: imf_public_debt_pct_gdp
        description: "General government gross debt as percentage of GDP"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: imf_primary_balance_pct_gdp
        description: "General government primary net lending/borrowing as percentage of GDP"
        tests:
          - column_range:
              min_value: -100
              max_value: 200
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: imf_current_account_balance
        description: "Current account balance in billions USD"
        tests:
          - column_range:
              min_value: -2000
              max_value: 1500
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: imf_ppp_conversion_rate
        description: "Purchasing power parity conversion rate"
        tests:
          - non_negative:
              config:
                warn_if: ">0"
                error_if: ">= 150"
      - name: imf_financial_development_index
        description: "Financial Development Index"
        tests:
          - column_range:
              min_value: 0
              max_value: 1
              config:
                warn_if: ">0"
                error_if: ">= 150"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - year
